### ISSUE TITLE
Conflicting with laravel/framework v5.4.8

### ISSUE THREAD

**Issue by unbolt** [nikolajlovenhardt/laravel-user-notifications#4]
laravel/framework v5.4.8 requires ramsey/uuid 3.5.2 (or at least that's what it has installed) which is preventing this package from installing.

Is there a way around this?

**Comment by nikolajlovenhardt** [comment]
@unbolt I'll fix this issue monday

**Comment by nikolajlovenhardt** [comment]
@unbolt You are welcome to open a PR, and change/update the uuid version.
